# Busybox builder image
FROM debian:bullseye-slim
USER root
COPY prepare_uclibc.sh /
RUN /prepare_uclibc.sh

# Busybox source directory
FROM busybox

# generate clean, final image for end users
FROM scratch
COPY --from=0 /usr/src/busybox/rootfs/. /
COPY --from=1 /etc/. /etc/
CMD ["./bin/sh"]
